### ISSUE TITLE
Discontinued/replaced NCBI gene id

### ISSUE THREAD

**Issue by Hao-Chalmers** [Ensembl/ensembl-datacheck#364]
### Description of the issue:
* Ensembl has been providing comprehensive annotation data for human, mouse and other species. It is very nice that Ensembl gene ids are also extensively associated with many other gene identifiers.
* It is found that the gene **ENSG00000114316** has been associated Entrez gene id **7375** and **107986084**. However, the [latter](https://www.ncbi.nlm.nih.gov/gene/?term=107986084) was discontinued by NCBI and replaced with the former. 

#### Expected feature/value/output:
* The discontinued/replaced NCBI ids can be updated to the latest ones

**Comment by james-monkeyshines** [comment]
Hello,
This repository is intended to check the data integrity of Ensembl databases, and does not relate to gene ID mapping.

Please contact the Ensembl helpdesk (http://www.ensembl.org/Help/Contact) with your query.
