### ISSUE TITLE
DisplayXrefExists.pm is not skipping non-vertebrates DBs

### ISSUE THREAD

**Issue by digrigor** [Ensembl/ensembl-datacheck#367]
Hi,

My name is Dio and I am working in the WormBase production team.

I was going through the Xref advisory datachecks fail messages for one of our pipelines and realised that the [DisplayXrefExists.pm](https://github.com/Ensembl/ensembl-datacheck/blob/release/104/lib/Bio/EnsEMBL/DataCheck/Checks/DisplayXrefExists.pm) was performing the datacheck even though our species.division='EnsemblParasite'

The subroutine skip_tests of the script runs fine (tested it locally with the failed db) so it must be an issue with any of the scripts that are calling it like. [DbCheck.pm](https://github.com/Ensembl/ensembl-datacheck/blob/release/104/lib/Bio/EnsEMBL/DataCheck/DbCheck.pm)

Feel free to email or slack me!

Best regards,
Dio

**Comment by james-monkeyshines** [comment]
This occurred because WormBase use older Ensembl release versions, and the division check was not yet implemented in the release/101 branch.
